name: Slack Daka EveryDay

on:
  # schedule:
  #   # UTC æ—¶é—´ï¼Œæ¯å¤©ä¸Šåˆ11ç‚¹30åˆ†
  #   - cron: '30 3 * * *'
  workflow_dispatch: 
    
jobs:
  send_message:
    outputs:
      ts: ${{ steps.notify.outputs.ts }}
    runs-on: ubuntu-latest
    steps:
    - name: Slack Send Message To Channel
      id: notify
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ vars.SLACK_CHANNEL_BLACK_HOLE }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "æ‰§è¡Œç»“æžœ: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": " Github æ‰§è¡Œç»“æžœ: ${{ job.status }},\n$ Next Line: {{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
        

    - name: Slack Message Status Check
      id: check_slack_status
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: ${{ vars.SLACK_CHANNEL_BLACK_HOLE }}
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "æ‰§è¡Œç»“æžœ: ${{ github.run_id }} Build ${{ github.run_number }} ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": " Github æ‰§è¡Œç»“æžœ2: ${{ github.run_id }} Build ${{ github.run_number }} ${{ job.status }}, outputs : ${{ steps.notify.outputs.ts }}\nNext Line: {{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
    - name: finally message
      run: |
        echo "::warning hhala:Missing semicolon"
        echo "AAA=halou" >> $GITHUB_OUTPUT
        echo "BBB=123" >> $GITHUB_OUTPUT
        echo "CCC=ðŸ˜­" >> $GITHUB_OUTPUT
        echo "DDD=:weary_face:" >> $GITHUB_OUTPUT
        echo $GITHUB_OUTPUT
    - name: finally message
      run: |
        echo "::warning hhala:Missing semicolon"
         
         
